name: Arduino Library CI

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arduino-platform:
          - 'cpc'
          - 'cpx_ada'
          - 'cpb'

    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    # manually install Servo
    - name: extra libraries
      if: matrix.arduino-platform != 'cpb'
      run: arduino-cli lib install "Servo"

    - name: test bluefruit platforms
      run: python3 ci/build_platform.py ${{ matrix.arduino-platform }}

    - name: clang
      run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" Adafruit_* 

    - name: doxygen
      env:
        GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
        PRETTYNAME : "Adafruit Circuit Playground Library"
      run: bash ci/doxy_gen_and_deploy.sh
